name: Format code

on:
  push:
    branches: [ master ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format code with black
        run: |
          pip install black
          black .
      - name: Create a new branch
        uses: actions/create-or-update-branch@v1
        with:
          branch: update-code
          commit-message: Update code
          create-pull-request: true
